version: '3.8'
services:
  mariadb:
    image: mariadb:jammy
    restart: always
    environment:
      MYSQL_USER: BigG
      MYSQL_PASSWORD: 1535
      MYSQL_ROOT_PASSWORD: root-secret-password
      MYSQL_DATABASE: Students
    volumes:
      - DatabaseSchoolValume:/var/lib/mysql
    networks:
      - GgNetwork

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    environment:
      PMA_ARBITRARY: '1'
    ports:
      - 8082:80
    networks:
      - GgNetwork
    depends_on:
      - mariadb

networks:
  GgNetwork:

volumes:
  DatabaseSchoolValume:
    external: true